site_name: NetDevOps.it
site_description: "Network & Infra Automation – Tutorials • Blog • Courses"
site_url: https://netdevops.it/
site_author: Bart Smeding
repo_url: https://github.com/bsmeding/bsmeding.github.io
edit_uri: edit/main/docs/

plugins:
  - blog:
      post_url_format: "{slug}"
      blog_toc: true
      pagination_per_page: 4
  - tags:
      tags_file: tags.md
  - search:
      lang: en
  - git-revision-date-localized
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date

nav:
  - Home: index.md
  - Nautobot:
    - 'Nautobot the ultimate network CMDB': nautobot_the_ultimate_network_cmdb.md
    - 'Nautobot Docker Apps': blog/posts/2025/2025-04-10-nautobot-docker-apps.md
    - 'Import Device Types into Nautobot': blog/posts/2025/2025-09-16-import-device-types-into-nautobot.md
    - 'Nautobot Digital Twin':
      - 'User Guide': projects/nautobot-digital-twin/user-guide.md
      - 'Admin Guide': projects/nautobot-digital-twin/admin-guide.md
      - 'Developer Guide': projects/nautobot-digital-twin/developer-guide.md
      - 'Release Notes': projects/nautobot-digital-twin/release-notes.md
    # - 'Nautobot Zero to Hero':
    #   - 'Overview': tutorials/nautobot_zero_to_hero/00_nautobot-zero-to-hero-landings-page.md
    #   - 'Part 1: Install Nautobot in 5 minutes': tutorials/nautobot_zero_to_hero/01_nautobot-zero-to-hero-part1.md
    #   - 'Part 2: Getting Started with Nautobot': tutorials/nautobot_zero_to_hero/02_nautobot-zero-to-hero-part2.md
    #   - 'Part 3: Deploy Network with Containerlab': tutorials/nautobot_zero_to_hero/03_nautobot-zero-to-hero-part3.md
    # - 'Nautobot Jobs': nautobot_jobs.md
    # - 'Nautobot Plugins': nautobot_plugins.md
  - Blog:
    - blog/index.md  
  - Tutorials:
    - 'Tutorials Overview': tutorials.md
    - 'Ansible Tutorial 1: Concepts & Terminology': tutorials/ansible_tutorial_1_concepts.md
    - 'Ansible Tutorial 2: Modules & Your First Playbook': tutorials/ansible_tutorial_2_modules.md
    - 'Ansible Tutorial 3: Variables, Modules & Network Fact Gathering': tutorials/ansible_tutorial_3_variables_facts.md
    - 'Ansible NAPALM': tutorials/ansible_cisco_napalm_diff.md
    - 'Git basics': tutorials/git_basics.md
    - 'Linux basics': tutorials/linux_basics.md
    - 'Enable Windows Subsystem for Linux': tutorials/enable_wsl_on_windows.md
    - 'Vagrant Installation': tutorials/vagrant_install.md
    - 'ContainerLab Getting Started': tutorials/containerlab_getting_started.md
    - 'ContainerLab Extended Configurations': tutorials/containerlab_extended_configurations.md
    - 'SSO: Introduction': sso.md
  - Tools:
    - 'Tools Index': tools.md
    - 'API': blog/posts/tools/api.md
    - 'Ansible': blog/posts/tools/ansible.md
    - 'CloudFormation': blog/posts/tools/cloudformation.md
    - 'ContainerLab': blog/posts/tools/containerlab.md
    - 'Docker': blog/posts/tools/docker.md
    - 'GitHub Actions': blog/posts/tools/github-actions.md
    - 'GitLab CI/CD': blog/posts/tools/gitlab-ci.md
    - 'Grafana': blog/posts/tools/grafana.md
    - 'InfluxDB': blog/posts/tools/influxdb.md
    - 'Jenkins': blog/posts/tools/jenkins.md
    - 'Jinja2': blog/posts/tools/jinja2.md
    - 'Nautobot': blog/posts/tools/nautobot.md
    - 'YAML': blog/posts/tools/yaml.md
    - 'NetBox': blog/posts/tools/netbox.md
    - 'NetPicker.io': blog/posts/tools/netpicker.md
    - 'Nornir': blog/posts/tools/nornir.md
    - 'OpsMill': blog/posts/tools/opsmill.md
    - 'Prometheus': blog/posts/tools/prometheus.md
    - 'pyATS': blog/posts/tools/pyats.md
    - 'SaltStack': blog/posts/tools/saltstack.md
    - 'SlurpIT.io': blog/posts/tools/slurpit.md
    - 'Terraform': blog/posts/tools/terraform.md
  - Web Tools:
    - 'Web Tools Overview': online-dev-tools/index.md
    - 'YAML Validator': online-dev-tools/yaml-validator.md
    - 'Regex Tester': online-dev-tools/regex-tester.md
    - 'JSON Validator': online-dev-tools/json-validator.md
    - 'Diff Tool': online-dev-tools/diff-tool.md
    - 'Base64 Converter': online-dev-tools/base64-converter.md
    - 'URL Encoder/Decoder': online-dev-tools/url-encoder.md
    - 'Hash Generator': online-dev-tools/hash-generator.md
    - 'Color Converter': online-dev-tools/color-converter.md
    - 'Rat of Fortune': wheel.md
  - Courses:
    - 'Courses': courses.md
    - 'Python for Network Engineers': courses/python-for-network-engineers.md
    - 'Ansible for Network Automation': courses/ansible-for-network-automation.md
    - 'Intro to Source of Truth': courses/intro-to-source-of-truth.md
    - 'Nautobot Closed Loop Automation': courses/nautobot-closed-loop-automation.md
    - 'Nautobot Job Development': courses/nautobot-job-development.md
    - 'Network Testing with Pytest and PyATS': courses/network-testing-pytest-pyats.md
    - 'Network Automation with PyATS': courses/network-automation-pyats.md
    - 'Network Unit Testing with NUTS': courses/network-unit-testing-nuts.md
    # - 'Cursussen Nederlands': courses_NL.md
    # - 'Python voor Netwerk Engineers': courses_NL/python-voor-netwerk-engineers.md
    # - 'Ansible voor Netwerk Automatisering': courses_NL/ansible-voor-netwerk-automatisering.md
    # - 'Introductie Source of Truth': courses_NL/intro-source-of-truth.md
    # - 'Nautobot Closed Loop Automatisering': courses_NL/nautobot-closed-loop-automatisering.md
    # - 'Nautobot Job Ontwikkeling': courses_NL/nautobot-job-ontwikkeling.md
    # - 'Netwerk Testen met Pytest en PyATS': courses_NL/netwerk-testen-pytest-pyats.md
    # - 'Netwerk Automatisering met PyATS': courses_NL/netwerk-automatisering-pyats.md
    # - 'Netwerk Unit Testen met NUTS': courses_NL/netwerk-unit-testen-nuts.md
  - Privacy Policy: privacy.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch theme
    - scheme: default
      primary: indigo
      accent: blue
    - scheme: slate
      primary: indigo
      accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.prune
    - content.code.copy
    - content.tabs.link
    - search.share
    - search.suggest

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html  
  - def_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences

## EXTRA
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bartsmeding/
  analytics:
    provider: google
    property: G-LF84C44PGC

extra_javascript:
  - js/giscus.js
  - https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js
  - js/cookieconsent-init.js
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenMax.min.js
  - https://cdn.jsdelivr.net/gh/zarocknz/javascript-winwheel@2.7.0/Winwheel.min.js
  - js/wheel.js

extra_css:
  - https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css
  - css/full-width.css
  - css/rat.css
